---
layout: cv
title: Kole Bauer's CV
---
# Kole Simmons Bauer
Computer/Data Scientist, Farmer, Student at BYU-I.

<div id="webaddress">
<a href="bau23015@byui.edu">bau23015@byui.edu</a>
| <a href="https://www.linkedin.com/in/kole-bauer-925a1215a">My LinkedIn Page</a>
</div>


## Currently

Pursuing a B.S. ins Computer Science with a Minor in Data Science and an emphasis in Machine Learning.

### Specialized in

Computer Science, Agriculture, 3D Design.

### Research interests

Quantitative Finance, Artificial Intelligence, Agriculture, Data in Agriculture.


## Education

`2007-2008`
__West Jefferson Elementary School__

`2008-2019`
__Madison High School__

`2019-2020`
__College of Eastern Idaho__

`2020-2021`
__Utah State University__

`2023-current`
__Brigham Young University - Idaho__


## Awards

`2014 Madison Junior High School Student of the Year`

`Idaho Entrepreneurship Competition 2023 Preliminary Finalist with Sigma Automotive Solutions`


## Occupation Experience

`2006-current`
__Bauer Farms__, Idaho

- Farm Hand
- Farm Manager
- Financial Assistant


`2018-2020, 2021`
__Webster's Inc.__, Idaho

 - Farm Hand
 - Operator


`2024-current`
__Bauer Family Dental | Sleep D.D.S. L.L.C.__, Idaho

- Technology Manager
- Bookkeeper
- Training and Onboarding


<!-- ### Footer

Last updated: July 2024 -->